SHOW VARIABLES LIKE "AUTOCOMMIT";

SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; -- (ACTIVE MVCC)
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ; -- (ACTIVE MVCC)
SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;

create simple database !
https://downloads.mysql.com/docs/employee-en.pdf

start TRANSACTION;
update, DELETE
commit by websocket

set open id for google;


https://www.tornadoweb.org/en/stable/auth.html